# Build using Visual Studio 2017 on Windows Server 2016.
# Variables with password stored in Azure secrets

trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  build_cake: './src/build.cake'

steps:

- task: UseNode@1
  inputs:
    script: 'npm --version'
  displayName: Installing Node 10


- task: DownloadSecureFile@1
  displayName: Download license
  name: license_file
  inputs:
    secureFile: 'license.xml'



- task: DownloadPipelineArtifact@2
  displayName: Download node modules
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'node_modules'
    targetPath: '$(Pipeline.Workspace)/s/src/node_modules'

- task: DownloadPipelineArtifact@2
  displayName: Download packages
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'packages'
    targetPath: '$(Pipeline.Workspace)/s/src/packages'

- task: DownloadPipelineArtifact@2
  displayName: Download tools
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'tools'
    targetPath: '$(Pipeline.Workspace)/s/src/tools'

- task: PowerShell@2
  displayName: Config preparation
  inputs:
    targetType: 'inline'
    script: |
      (Get-Content $(build_cake)) -replace "MSBuildToolVersion.VS201\d{1,3}", '$(agent_buildTools)' | Set-Content $(build_cake)
      move $(license_file.secureFilePath) ./src/ -Force



- task: gulp@1
  displayName: Gulp code generation
  inputs:
    gulpFile: './src/scripts/code-generation/codeGen.js'
    targets: 
    enableCodeCoverage: false

- task: PowerShell@2
  displayName: Webpack build
  inputs:
    targetType: 'inline'
    script: |
      ./src/node_modules/.bin/copyfiles.cmd -f  ./src/Project/HCA/client/public/**/* ./src/Project/HCA/client/build/
      ./src/node_modules/.bin/cross-env NODE_ENV=production webpack
      ./src/tools/nuget.exe restore ./src/HCA.sln

- task: MSBuild@1
  displayName: MSBuild
  inputs:
    solution: './src/HCA.sln'
    msbuildVersion: '15.0'
    msbuildArchitecture: 'x86'
    configuration: 'Debug'
    msbuildArguments: '/t:Rebuild'

- task: PowerShell@2
  inputs:
    filePath: './src/build.ps1'
    arguments: '-Target 003-Tests'
    workingDirectory: './src/'
  displayName: Test
