# Build using Visual Studio 2017 on Windows Server 2016.
# Variables with password stored in Azure secrets

trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  build_cake: './src/build.cake'

steps:

- task: UseNode@1
  displayName: Installing Node 10
  inputs:
    script: 'npm --version'

- task: DownloadSecureFile@1
  displayName: Download license
  name: license_file
  inputs:
    secureFile: 'license.xml'

- task: DownloadPipelineArtifact@2
  displayName: Download node modules
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'node_modules'
    targetPath: '$(Pipeline.Workspace)/s/src/node_modules'

- task: DownloadPipelineArtifact@2
  displayName: Download packages
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'packages'
    targetPath: '$(Pipeline.Workspace)/s/src/packages'

- task: DownloadPipelineArtifact@2
  displayName: Download tools
  inputs:
    buildType: 'specific'
    project: 'c8a112df-eb95-41fa-bb80-48e83128fe75'
    definition: '10'
    buildVersionToDownload: 'latest'
    artifactName: 'tools'
    targetPath: '$(Pipeline.Workspace)/s/src/tools'

- task: PowerShell@2
  displayName: Config preparation
  inputs:
    targetType: 'inline'
    script: |
      Move-Item $(license_file.secureFilePath) ./src/ -Force

- task: gulp@1
  displayName: Gulp code generation
  inputs:
    gulpFile: './src/scripts/code-generation/codeGen.js'
    targets: 
    enableCodeCoverage: false

- task: PowerShell@2
  displayName: Webpack build
  inputs:
    targetType: 'inline'
    script: |
      # $env:path="$env:path;$(Pipeline.Workspace)/s/src/node_modules/.bin"
      # $env:path="$env:path;$(Pipeline.Workspace)/s/src/tools"
      $(Pipeline.Workspace)/s/src/node_modules/.bin/copyfiles.cmd -f  ./src/Project/HCA/client/public/**/* ./src/Project/HCA/client/build/
      $(Pipeline.Workspace)/s/src/node_modules/.bin/cross-env.cmd NODE_ENV=production $(Pipeline.Workspace)/s/src/node_modules/.bin/webpack.cmd
      $(Pipeline.Workspace)/s/src/tools/nuget.exe restore ./src/HCA.sln

- task: MSBuild@1
  displayName: MSBuild
  inputs:
    solution: './src/HCA.sln'
    msbuildVersion: '15.0'
    configuration: 'Debug'
    msbuildArguments: '/t:Rebuild'

- task: PowerShell@2
  displayName: Run Unit tests
  inputs:
    filePath: './src/build.ps1'
    arguments: '-Target 003-Tests'
    workingDirectory: './src/'

- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
      $env:path="$env:path;$(Pipeline.Workspace)/s/src/node_modules/.bin"
      $env:path="$env:path;$(Pipeline.Workspace)/s/src/tools"
      copyfiles -f  ./src/Project/HCA/client/public/**/* ./src/Project/HCA/client/build/
      cross-env NODE_ENV=production webpack
      nuget.exe restore ./src/HCA.sln
    workingDirectory: './src/'
 
- task: PublishCodeCoverageResults@1
  displayName: Publish code coverage
  inputs:
    codeCoverageTool: 'Cobertura'
    summaryFileLocation: '$(Pipeline.Workspace)/s/output/tests/coverage/cobertura-coverage.xml'

- task: PowerShell@2
  displayName: Collect files for artifacts
  env:
    Workspace: $(Pipeline.Workspace)
  inputs:
    targetType: 'inline'
    script: |
      Copy-Item $(Pipeline.Workspace)/s/src/configs/Sitecore/Web.config $(Pipeline.Workspace)/s/output/web.config -Force
      ./automation/Get-Artifacts.ps1 Feature
      ./automation/Get-Artifacts.ps1 Foundation
      ./automation/Get-Artifacts.ps1 Project
    errorActionPreference: 'continue'
    ignoreLASTEXITCODE: true
      

- task: PublishPipelineArtifact@1
  displayName: Publish web config
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/output/web.config'
    artifact: 'web_config'
    publishLocation: 'pipeline'
 
 
- task: PublishPipelineArtifact@1
  displayName: Publish unicorn
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/output/unicorn'
    artifact: 'unicorn'
    publishLocation: 'pipeline'
    
- task: PublishPipelineArtifact@1
  displayName: Publish Feature 
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/output/Feature'
    artifact: 'Feature'
    publishLocation: 'pipeline'
    
- task: PublishPipelineArtifact@1
  displayName: Publish Foundation 
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/output/Foundation'
    artifact: 'Foundation'
    publishLocation: 'pipeline'
    
- task: PublishPipelineArtifact@1
  displayName: Publish Project 
  inputs:
    targetPath: '$(Pipeline.Workspace)/s/output/Project'
    artifact: 'Project'
    publishLocation: 'pipeline'
