trigger: none

pool:
  vmImage: 'vs2017-win2016'

variables:
  version_file: './automation/version'

jobs:
  - job: Get_build_version

    steps:
    - task: PowerShell@2
      displayName: 'Get version variable'
      env:
        PAT: $(PAT)
      inputs:
        targetType: 'inline'
        script: |
          $Token = $env:PAT
          $Base64Token = [System.Convert]::ToBase64String([char[]]$Token)

          $Headers = @{
              Authorization = 'Basic {0}' -f $Base64Token;
              }

          $ReleaseList = (Invoke-RestMethod -Headers $Headers -Uri https://api.github.com/repos/epam/sitecore-headless-commerce-accelerator/branches -Method Get).name | Where-Object { $_.Contains("release")}
          $LastReleaseNumber = $ReleaseList[-1].Split("/")[1]
          $MajorVersionNumber = $LastReleaseNumber.Split(".")[0]
          $MinorVersionNumber = $LastReleaseNumber.Split(".")[1]/1 + 1
          $PatchVersionNumber = $LastReleaseNumber.Split(".")[2]
          $VersionNumber = $MajorVersionNumber + "." + $MinorVersionNumber + "." + $PatchVersionNumber
          $LastVersion = "$(HCA_Version)".Split("-")[1]
          if ($VersionNumber -ne $LastVersion) {
            $BranchVersion = $VersionNumber + "-$(branch_revision)"
          }
          else {
            $BranchVersion = "$(HCA_Version)"
          }
          Write-Host "##vso[task.setvariable variable=BranchVersion]$BranchVersion"
          Write-Host "$env:PAT"

    - task: Bash@3
      displayName: 'Set version variable'
      inputs:
        targetType: 'inline'
        script: |
          curl -fL -XPUT -H "Authorization:Bearer $(System.AccessToken)" -H "Content-Type:application/json" \
            -d '{
              "id": "$(HCA_Version_Variable_Group_ID)",
              "type": "Vsts",
              "name": "HCA_Version",
              "variables": {
                "HCA_Version_Variable_Group_ID": {
                "isSecret": false,
                "value": "$(HCA_Version_Variable_Group_ID)"
                },
              "HCA_Version": {
                "isSecret": false,
                "value": "$(BranchVersion)"
                }
              }
            }' \
            $(System.TeamFoundationCollectionUri)/$(TeamProject)/_apis/distributedtask/variablegroups/$(HCA_Version_Variable_Group_ID)?api-version=5.0-preview.1

  - job: Set_build_version
    dependsOn: Get_build_version
    variables:
      ReleaseVersionNumber: $[counter(variables['HCA_Version'], 1)]
    
    steps:
    - task: PowerShell@2
      displayName: 'Set build version'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "##vso[build.updatebuildnumber]$(HCA_Version).$(ReleaseVersionNumber)"

  - job: Test_build_version
    dependsOn: Set_build_version

    steps:
    - task: PowerShell@2
      displayName: 'Test build version'
      inputs:
        targetType: 'inline'
        script: |
          Write-Host "$(Build.BuildNumber)"

  - job: Publish_repository
    dependsOn: Set_build_version

    variables:
      npm_package_config_folder: './generators/generators/templates/src'
      npm_package_config: '$(npm_package_config_folder)/package.json'

    steps:

    - task: PowerShell@2
      displayName: Download node modules
      inputs:
        targetType: 'inline'
        script: 'npm install gulp-cli'
        workingDirectory: './generators'

    - task: gulp@1
      displayName: Collect necessary files to templates
      inputs:
        gulpFile: './generators/gulpfile.js'
        targets: 
        enableCodeCoverage: false

    - task: PowerShell@2
      displayName: Update package.json
      inputs:
        targetType: 'inline'
        script: |
          (Get-Content $(npm_package_config)) -replace '"name": $(quotes_regexp)', '"name": "$(project_name)"' | Set-Content $(npm_package_config)
          (Get-Content $(npm_package_config)) -replace '"version": $(quotes_regexp)', '"version": "$(Build.BuildNumber)"' | Set-Content $(npm_package_config)
          
    - task: PowerShell@2
      displayName: Create package
      inputs:
        targetType: 'inline'
        script: |
          npm pack $(npm_package_config_folder)

    - task: PowerShell@2
      displayName: Publish package
      env:
        npm_auth_token: $(npm_auth_token)
      inputs:
        targetType: 'inline'
        script: |
          "//registry.npmjs.org/:_authToken=$env:npm_auth_token`n" | out-file "$env:userprofile\.npmrc" -Encoding ASCII
          npm publish --loglevel=error